// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUXTof8c0R0Hd9rw5x8vLVilPwl6jOHCs',
    appId: '1:721678147898:web:7edf81de3b5c0d3ea33003',
    messagingSenderId: '721678147898',
    projectId: 'practicalofchatuser',
    authDomain: 'practicalofchatuser.firebaseapp.com',
    storageBucket: 'practicalofchatuser.appspot.com',
    measurementId: 'G-E3XCPTP5MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYBIhgiCJ4059MQQcBB2fTAHOCRiPk0Vg',
    appId: '1:721678147898:android:ce13c7c36f30fecba33003',
    messagingSenderId: '721678147898',
    projectId: 'practicalofchatuser',
    storageBucket: 'practicalofchatuser.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkdcbjP2rAg6r1Xsc2FLhCwXdqeIv0Gi0',
    appId: '1:721678147898:ios:d4e79f372a0c2055a33003',
    messagingSenderId: '721678147898',
    projectId: 'practicalofchatuser',
    storageBucket: 'practicalofchatuser.appspot.com',
    iosClientId:
        '721678147898-bbfeumd7m9079mdkfekrstiugqtpdelh.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkdcbjP2rAg6r1Xsc2FLhCwXdqeIv0Gi0',
    appId: '1:721678147898:ios:34f9eb5ae3fe49d6a33003',
    messagingSenderId: '721678147898',
    projectId: 'practicalofchatuser',
    storageBucket: 'practicalofchatuser.appspot.com',
    iosClientId:
        '721678147898-h9jdfteqak53pef4pf8sqkgig1nmdo5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstProject.RunnerTests',
  );
}
